version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - MODE=DEV
    ports:
      - 8990:8990
    volumes:
      - .:/code
    depends_on:
      - db
    command: /bin/bash -c "exec invoke run"
