version: '3'
services:
  db:
    image: postgres
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure
# probably will be needed further
#  redis:
#    image: redis:latest
#    ports:
#      - 6379:6379
  web:
    build: .
    environment:
      - MODE=DEV
    ports:
      - 8990:8990
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbitmq
    command: /bin/bash -c "exec invoke run"
